name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t tanujkumar46/springboot-example .
      - name: Publish image to docker hub
        run: docker push tanujkumar46/springboot-example:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull tanujkumar46/springboot-example:latest
      - name: Delete old container
        run: sudo docker rm -f springboot-example-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name springboot-example-container tanujkumar46/springboot-example
